name: python-perf
channels:
  - conda-forge
dependencies:
  # Basic packages
  - numpy
  - scipy
  - pandas
  - matplotlib-base
  - ipympl
  # Profiling
  - pyperf
  - line_profiler
  - snakeviz
  - py-spy
  # Optimization
  - numexpr
  - cython
  - numba
  - pythran
  - clangdev
  - transonic
  # Parallelization
  - mpi4py
  - openmpi
  - dask
  - dask-labextension
  # Tools
  - ipython
  - graphviz
  - python-graphviz
  - ipywidgets
  - widgetsnbextension 
  - jupyter
  - jupyterlab
